### ISSUE TITLE
Credit Ben Briggs

### ISSUE THREAD

**Issue by andyjansson** [simplaio/gulp-rucksack#1]
Since this package is a derived from https://github.com/ben-eb/gulp-cssnano you need to include his [license](https://github.com/ben-eb/gulp-cssnano/blob/master/LICENSE-MIT) to remain compliant with it. Also, you might want to include a credit somewhere in the README.md.

**Comment by seaneking** [comment]
Yep, you’re absolutely right, sorry. I was in such a rush to get these plugins out I just chucked in my boilerplate README and such :-/ 

I’ve added his license and a credit note at the top of the README.

**Comment by ben-eb** [comment]
Thanks. :+1:
